version: "3"

services:
  next:
    container_name: next-dev
    image: next-dev:tea42
    build:
      context: service/
      dockerfile: Dockerfile
    volumes:
      - front_repo:/usr/app/srcs
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always

volumes:
  front_repo:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}"
